title: Hallo World!
author: Bernard
email: bernard3135@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I a beginner in GitHub
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
